Resources:
  SQSPIRSensor:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PIR-queue
      Tags:
        - Key: "Name"
          Value: PIR-queue
        - Key: "Template"
          Value: smart_spaces
        - Key: "Environment"
          Value: dev
        - Key: "Purpose"
          Value: "PIR queue to offload massive data injection to DynamoDB"
        - Key: "Creation_Date"
          Value: "Tue_June_23"
