# serverless.yml

plugins:
  - serverless-offline

service: smart-spaces

custom:
  sensorTableName: "SensorTable"
  roomTableName: "RoomTable"
  userTableName: "UserTable"
  queueName: "SensorQueue"

provider:
  name: aws
  runtime: nodejs12.x
  stage: new
  region: us-east-1

functions:
  roomData:
    handler: room.handler
    events:
      - http:
          path: "/getRooms"
          method: get
      - http:
          path: "/postRooms"
          method: post

  queueSensor:
    handler: queue.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:130193131803:${self:custom.queueName}
          batchSize: 10

