# serverless.yml

plugins:
  - serverless-offline

service: motion-detection-service

custom:
  pirTableName: "PIR-table"
  userTableName: "User-table"
  favoriteTableName: "Favorite-table"
  queueName: "PIR-queue"
  cognitoName: "PIR-cognito"
  application: "smart-spaces"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PIRSensor", "Arn"] }
        - { "Fn::GetAtt": ["FavoriteTable", "Arn"] }
        - { "Fn::GetAtt": ["UserTable", "Arn"] }
  environment:
    PIR_TABLE: ${self:custom.pirTableName}
    USER_TABLE: ${self:custom.userTableName}
    FAVORITE_TABLE: ${self:custom.favoriteTableName}

functions:
  getPhoneRoomData:
    handler: motion.handler
    events:
      - http:
          # path: "/sensor/{proxy+}"
          # method: get
          # request:
          #   template:
          #     application/json: '{ "floor": "$input.params(''floor'')" }'
          path: "/sensor"
          method: post
      - http:
          path: "/users/{proxy+}"
          method: get
          # request:
          #   template:
          #     application/json: '{ "floor": "$input.params(''floor'')" }'
      - http:
          path: "/users"
          method: post
      - http:
          path: "/users"
          method: put

  queueHandler:
    handler: queue.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:130193131803:${self:custom.queueName}
          batchSize: 10

resources:
  # DDB
  - ${file(resources/ddb_serverless.yml)}
  # SQS
  - ${file(resources/sqs_serverless.yml)}
  # Cognito
  - ${file(resources/cognito_serverless.yml)}
