# serverless.yml

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: smart-spaces

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SensorTable", "Arn"] }
        - { "Fn::GetAtt": ["RoomTable", "Arn"] }
        - { "Fn::GetAtt": ["UserTable", "Arn"] }
  environment:
    SENSOR_TABLE: ${env:DDBSENSOR}
    ROOM_TABLE: ${env:DDBROOM}
    USER_TABLE: ${env:DDBUSER}

functions:
  userFunction:
    handler: user.handler
    events:
      - http:
          path: "/postUsers"
          method: post
      - http:
          path: "/changeUserPass"
          method: put

  roomData:
    handler: room.handler
    events:
      - http:
          path: "/getRooms/{proxy+}"
          method: get
      - http:
          path: "/postRooms"
          method: post

  queueHandler:
    handler: queue.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:130193131803:${env:QUEUE}
          batchSize: 10

resources:
  # DDB
  - ${file(resources/ddb_serverless.yml)}
  # SQS
  - ${file(resources/sqs_serverless.yml)}
  # Cognito
  - ${file(resources/cognito_serverless.yml)}
