# serverless.yml

plugins:
  - serverless-offline

service: motion-detection-service

custom:
  pirTableName: "PIR-table"
  phoneRoomTableName: "Phone-room-table"
  favoriteTableName: "Favorite-table"
  queueName: "PIR-queue"
  cognitoName: "PIR-cognito"
  application: "smart-spaces"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PIRSensor", "Arn"] }
        - { "Fn::GetAtt": ["FavoriteTable", "Arn"] }
        - { "Fn::GetAtt": ["PhoneRoomTable", "Arn"] }
  environment:
    PIR_TABLE: ${self:custom.pirTableName}
    PHONE_ROOM_TABLE: ${self:custom.phoneRoomTableName}
    FAVORITE_TABLE: ${self:custom.favoriteTableName}

functions:
  getPhoneRoomData:
    handler: motion.handler
    events:
      - http: "GET /sensor/{proxy+}"
      - http: "GET /phonerooms/{proxy+}"
      - http: "GET /favorites"
      - http: "POST /favorites"
      - http: "DELETE /favorites"
  queueHandler:
    handler: queue.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:130193131803:${self:custom.queueName}
          batchSize: 10

resources:
  # DDB
  - ${file(resources/ddb_serverless.yml)}
  # SQS
  - ${file(resources/sqs_serverless.yml)}
  # Cognito
  - ${file(resources/cognito_serverless.yml)}
