# serverless.yml

plugins:
  - serverless-offline

service: motion-detection-service

custom:
  tableName: "PIR-table"
  queueName: "PIR-queue"
  cognitoName: "PIR-cognito"
  application: "smart-spaces"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PIRSensor", "Arn"] }
  environment:
    PIR_TABLE: ${self:custom.tableName}

functions:
  getSensorData:
    handler: motion.handler
    events:
      - http: "GET /sensor/{proxy+}"
  queueHandler:
    handler: queue.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:130193131803:${self:custom.queueName}
          batchSize: 10
  # userAuth:
  #   handler: user.handler
  #   events:
  #     - http: "GET /user/:userId"
  # userSignUp:
  #   handler: user.handler
  #   events:
  #     - http: "POST /user/"

resources:
  # DDB
  - ${file(resources/ddb_serverless.yml)}
  # SQS
  - ${file(resources/sqs_serverless.yml)}
  # Cognito
  - ${file(resources/cognito_serverless.yml)}
