export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const STARS = 'STARS'; // this might not be necessary, let's see
// export const ADD_ROOMS = 'ADD_ROOMS';
export const ADD_ROOMS_A = 'ADD_ROOMS_A';
export const ADD_ROOMS_U = 'ADD_ROOMS_U';
export const FAV_ROOMS = 'FAV_ROOMS';
// export const UI_START_LOADING = 'UI_START_LOADING';
// export const UI_STOP_LOADING = 'UI_STOP_LOADING';